[package]
name = "borink-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
thiserror = "2"
sha2 = "0.10.8"
typenum = { version = "1", features = ["const-generics"] }
generic-array = { version = "1" }